### ISSUE TITLE
Is not possible update an user name and/or email

### ISSUE THREAD

**Issue by DiegoVictor** [tukno/meetapp#6]
When validating the comming data is expected (optionally) the `name` and `email` field but posteriorly to get request's data is used `nameReq` and `emailReq` instead:

```js
// UserController.js:56
const schema = Yup.object().shape({
      name: Yup.string(),
      email: Yup.string().email(),
      [...]
```

```js
// UserController.js:78
const {
      nameReq,
      emailReq,
     [...]
} = req.body;
```

So the name and email sent in the request is never used

**Comment by tukno** [comment]
Hello, I fixed it, I cant remember why I made this decision but in practice was like trading six of one for half a dozen of the other haha. I also refactored the validation process in 2feb30d4cefdda79cd9662754253e4d5b82eb174, if you do not mind, could you take a look?
