### ISSUE TITLE
Could/Should this error message be improved?

### ISSUE THREAD

**Issue by DiegoVictor** [tukno/meetapp#7]
I think this error message could be improved, when sending requests with `password` and `confirmPassword` fields we get the error message 'Password is required':
```js
if (!oldPassword && (password || confirmPassword)) {
      return res.status(401).json({ error: 'Password is required' });
}
```
Suggestions:
'Old password is missing'
'Old password is required'
'To update your password provide the old one'

**Comment by tukno** [comment]
Agreed, I updated the message to be more concise.
Thank you!
